// Reader-facing wording of the comments block, as discussion-rules.md fixes it. Russian only for
// now; the bilingual front is a later step, and this is the one file it will touch here.
export const strings = {
    heading: 'Комментарии',
    loading: 'Загрузка…',
    none: 'Пока нет комментариев',
    loadFailed: 'Не удалось загрузить комментарии',
    offline: 'Нет подключения к интернету',
    retry: 'Повторить',
    more: 'Показать ещё',
    moreFailed: 'Не удалось загрузить',
    showReplies: (count: number) => `Показать ответы (${count})`,
    moreReplies: 'Показать ещё ответы',
    repliesFailed: 'Не удалось загрузить ответы',
    noRepliesLeft: 'Ответов больше нет',
    ignoring: 'Вы игнорируете автора',
    reveal: 'Показать',
    hidden: 'Скрытый комментарий',
    deleted: 'Комментарий удалён',
    removed: 'Комментарий удалён модерацией',
    // instead of the name, for an author under a restriction (§2.8)
    restricted: 'заблокирован',
    // a visible comment whose author user-service does not know
    nobody: 'Пользователь',
    allComments: 'Ко всем комментариям',
    missing: 'Комментарий не найден',
    inReplyTo: 'В ответ на',

    // writing (§4, §5, §12)
    signInToComment: 'Войдите, чтобы комментировать',
    signInToReply: 'Войдите, чтобы ответить',
    sessionExpired: 'Сессия истекла, войдите снова',
    signIn: 'Войти',
    reply: 'Ответить',
    send: 'Отправить',
    sending: 'Отправка…',
    cancel: 'Отмена',
    yourComment: 'Ваш комментарий',
    yourReply: 'Ваш ответ',
    counter: (length: number, max: number) => `${length} / ${max}`,
    tooLong: (max: number) => `Не больше ${max} символов`,
    tooManyLinks: (max: number) => `Не больше ${max} ссылок в комментарии`,
    sendFailed: 'Не удалось отправить',
    tooOften: 'Слишком часто, попробуйте позже',
    parentDeleted: 'Комментарий, на который вы отвечаете, удалён',
    postAsNew: 'Опубликовать как новый комментарий',
    mutedByRecipient: 'Автор комментария вас игнорирует — ваш ответ у него скрыт',
    restrictedUntil: (when: string) => `Вы не можете комментировать до ${when}`,
    restrictedIndefinitely: 'Комментирование недоступно',
}
